import fs from 'node:fs';
const m = JSON.parse(fs.readFileSync(new URL('artifacts.json', import.meta.url), 'utf8'));
const artifact = a => `Artifact { file: ${JSON.stringify(a.file)}, url: ${JSON.stringify(a.url ?? '')}, bytes: ${a.bytes}, sha256: ${JSON.stringify(a.sha256)} }`;
const code = `// Generated by scripts/english-runtime/generate-catalog.mjs; selected STT only.\nuse crate::stt::local::catalog::Artifact;\npub const ID: &str = "moonshine-small-streaming-en";\npub const RUNTIME: Artifact = ${artifact(m.runtime)};\npub const FILES: &[Artifact] = &[\n${m.artifacts.filter(a => a.kind === 'stt').map(artifact).join(',\n')}\n];\npub const DLLS: &[Artifact] = &[\n${m.runtime.members.map(artifact).join(',\n')}\n];\npub const ENTRIES: &[&str] = &${JSON.stringify(m.runtime.members.map(a => a.entry))};\n`;
fs.mkdirSync('src-tauri/src/stt/moonshine', { recursive: true });
fs.writeFileSync('src-tauri/src/stt/moonshine/catalog.rs', code);
