import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (root, path) => JSON.parse(readFileSync(resolve(root, path), 'utf8'));
const cell = (value) => String(value).replaceAll('|', '\\|').replace(/[\r\n]+/g, ' ');

/** Deterministic view: recorded facts only, never checkout name or wall-clock time. */
export function renderStatus(root = ROOT) {
  const project = readJson(root, 'docs/context/project.json');
  const pkg = readJson(root, 'package.json');
  const active = project.active_workstream;
  if (active !== null && (typeof active !== 'string' || !/^[a-z0-9]+(?:[.-][a-z0-9]+)*$/.test(active))) {
    throw new Error('active_workstream: invalid ID');
  }
  const series = active === null ? null : readJson(root, `docs/workstreams/${active}/state.json`);
  const out = [
    '<!-- Generated by scripts/context-status.mjs. Edit JSON sources, then pnpm context:refresh. -->',
    '# Глагол — текущее состояние', '',
    `Исходники: **${cell(pkg.version)}**. Дата общих наблюдений: ${project.observed_at}.`, '',
    'Начало работы: [AGENTS](../AGENTS.md) → этот обзор → состояние и журнал серии.', '',
  ];
  if (series) {
    const step = series.steps.find((s) => s.id === series.next);
    out.push(`Выбранная серия: **${cell(series.title)}**.`, '',
      `**NEXT: ${cell(series.next)} — ${cell(step?.title ?? 'НЕИЗВЕСТНЫЙ ШАГ')}** (${cell(step?.status)}).`, '',
      `[Решения](workstreams/${active}/README.md) · [Состояние](workstreams/${active}/state.json) · [Журнал](workstreams/${active}/log.md)`, '');
    if (series.claim) out.push(`Выполняет: ${cell(series.claim.owner)}; ветка ${cell(series.claim.branch)}; с ${series.claim.at}.`, '');
    for (const s of series.steps.filter((s) => s.status === 'blocked')) out.push(`Блокер ${s.id}: ${cell(s.reason)}.`, '');
    const done = [...series.steps].reverse().find((s) => s.status === 'done');
    if (done) {
      const check = done.checks.find((c) => c.status === 'PASS');
      out.push(`Последний завершённый шаг серии: **${cell(done.id)} — ${cell(done.title)}**.`, '',
        `Проверка ${check.at}: ${cell(check.output)} ([evidence](../${check.evidence})).`, '');
    } else out.push('В этой серии ещё нет завершённых шагов. Предыдущие результаты — в связанных журналах.', '');
  } else out.push('Активная серия не выбрана. Новая задача определяется пользователем.', '');
  out.push('## Доставка и наблюдения', '', '| Что | Статус / дата | Наблюдение |', '|---|---|---|');
  for (const o of project.observations) out.push(`| ${cell(o.label)} | ${cell(o.status)} / ${o.observed_at} | ${cell(o.summary)} ([источник](../${o.source})) |`);
  out.push('', '## История и продолжение', '');
  for (const p of project.links) out.push(`- [${p}](../${p})`);
  out.push('', 'PASS в старом журнале — результат той даты, не новая проверка. Сборка, установка и публикация учитываются отдельно.', '');
  return out.join('\n');
}

export function statusMatches(root = ROOT) {
  return readFileSync(resolve(root, 'docs/STATUS.md'), 'utf8').replaceAll('\r\n', '\n') === renderStatus(root);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2] ?? 'check';
  try {
    if (!['write', 'check'].includes(mode)) throw new Error('Use write or check');
    if (mode === 'write') writeFileSync(resolve(ROOT, 'docs/STATUS.md'), renderStatus());
    else if (!statusMatches()) throw new Error('docs/STATUS.md is stale: run pnpm context:refresh');
    console.log(`context-status ${mode}: OK`);
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
