// Generated by scripts/english-runtime/generate-catalog.mjs; selected STT only.
use crate::stt::local::catalog::Artifact;
pub const ID: &str = "moonshine-small-streaming-en";
pub const RUNTIME: Artifact = Artifact { file: "runtime.whl", url: "https://files.pythonhosted.org/packages/ea/05/ad3457baa56170a13829c98327598a4d99d6cd4bdff8ae59df4c47ebdd11/moonshine_voice-0.1.5-py3-none-win_amd64.whl", bytes: 16542073, sha256: "7fc9a84e827360ddb85c2735f44a1502c5575c27dcb476a2555646cd20a70e9d" };
pub const FILES: &[Artifact] = &[
Artifact { file: "stt/adapter.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/adapter.ort", bytes: 2870368, sha256: "c665f742364febad597cc9ac1e0b341ffbee0e24a1466e2f3bde95e6e4771762" },
Artifact { file: "stt/cross_kv.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/cross_kv.ort", bytes: 5356536, sha256: "e2d3417144e9514055ebfefe8dcc4c0a55a55adcb8530435844c75c53e352bf6" },
Artifact { file: "stt/decoder_kv.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/decoder_kv.ort", bytes: 81878600, sha256: "1a05465b1dd955858dfcbee039c0020fb5dd982b0f5094c34e61735d518d771b" },
Artifact { file: "stt/encoder.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/encoder.ort", bytes: 44148576, sha256: "2d4d973e91e8aca08c51e7e7efa28a46ab265b63d809d5294d18b86bcd85b993" },
Artifact { file: "stt/frontend.model.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/frontend.model.ort", bytes: 26944, sha256: "09b1210ae30dc5f0f3e45f0ebab914c254741323114f53fbbe5ae62cca35058f" },
Artifact { file: "stt/frontend.weights.ort", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/frontend.weights.ort", bytes: 7769464, sha256: "7ef97521bd4bad3928f5bb6808586f4fcc6e92bd5990394112eed7d4052ec338" },
Artifact { file: "stt/streaming_config.json", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/streaming_config.json", bytes: 512, sha256: "26f02b6afb22d60871a5efd85c3d38e569cc0ddb6c5eb6e93d3260152ae8a47a" },
Artifact { file: "stt/tokenizer.bin", url: "https://huggingface.co/moonshine-ai/moonshine-voice-assets/resolve/0bf2f2e5aff22e6fbba4300b00a4e00bbc4f8aae/model/small-streaming-en/quantized_26_08_21/tokenizer.bin", bytes: 249974, sha256: "6884b35fd6377d4c4d32336a0bc152f36b64d1e45b6503683cdc238250a8472d" }
];
pub const DLLS: &[Artifact] = &[
    Artifact {
        file: "native/moonshine.dll",
        url: "",
        bytes: 9595392,
        sha256: "5785b084680b7cb335e95b2e99e9c243e4b15833a30b1add5a4598694f8b48aa",
    },
    Artifact {
        file: "native/onnxruntime.dll",
        url: "",
        bytes: 14186016,
        sha256: "dec964ab1ee36cc9b0ae247d13b376627992fc57dec0454354017ab8fd84f1ea",
    },
];
pub const ENTRIES: &[&str] = &[
    "moonshine_voice/moonshine.dll",
    "moonshine_voice/onnxruntime.dll",
];
